apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-deploy
  namespace: testns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first
  template:
    metadata:
      labels:
        app: first
    spec:
      containers:
      - name: first
        image: practiced/new-pipeline-1:24
        ports:
        - containerPort: 8080
